#!/usr/bin/env python3
"""Regenerate the site's HTML pages from one shared shell.

Every page carries the same head, header and footer. Holding that in one
place means a nav change is a single edit rather than five, and no page can
quietly drift out of step with the others.

    python3 build.py

publish.sh runs this before every commit, so the HTML in the repo is always
this file's output. Edit this file, never the .html files: they are
overwritten on the next build.
"""
import pathlib

BANNER = "<!-- Generated by build.py. Edit build.py, not this file. -->"

# (file, i18n key for the nav label, fallback text)
NAV = [
    ("work.html", "nav.work", "Work"),
    ("talks.html", "nav.talks", "Community"),
    ("approach.html", "nav.approach", "Approach"),
    ("contact.html", "nav.contact", "Contact"),
]

CURRENT = ' aria-current="page"'

HEAD = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title data-i18n="__TITLE_KEY__">__STATIC_TITLE__</title>
<meta name="description" data-i18n="site.description" data-i18n-attr="content" content="__STATIC_DESC__">
<link rel="canonical" href="__CANONICAL__">

<meta property="og:type" content="website">
<meta property="og:site_name" content="kaixinbuilds">
<meta property="og:title" content="__STATIC_TITLE__">
<meta property="og:description" content="__STATIC_DESC__">
<meta property="og:url" content="__CANONICAL__">
<meta property="og:image" content="__SHARE_IMAGE__">
<meta name="twitter:card" content="summary_large_image">
<meta name="color-scheme" content="light dark">
<meta name="theme-color" content="#1E2749">

<!-- Spectral for headings and epigraphs, Inter for body and UI. Chinese
     resolves to the system serif (Songti SC / Source Han Serif): a webfont
     with CJK coverage would cost megabytes for one page. -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Spectral:ital,wght@0,400;0,600;1,400&display=swap" rel="stylesheet">

<link rel="stylesheet" href="style.css">
<link rel="icon" href="favicon.png" sizes="48x48">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
</head>
<body>

<a class="skip-link" href="#main">Skip to content</a>

<header class="site-header">
  <div class="wrap">
    <div class="header-inner">
      <a class="wordmark" href="index.html"__HOME__>
        <span class="wordmark-text">kaixin<em>builds</em></span>
      </a>

      <nav class="site-nav" aria-label="Primary">
__NAV__      </nav>

      <button id="lang-toggle" class="lang-toggle" type="button"
              data-i18n="lang.switchTo"
              data-i18n-aria-label="lang.ariaLabel">切换中文</button>
    </div>
  </div>
</header>

"""

TAIL = """\


<script src="script.js"></script>
</body>
</html>
"""

SITE = "https://kaixinbuilds.github.io"
SHARE_IMAGE = SITE + "/assets/screenshots/vocabsummit-landing.jpg"

# (static <title>, static description) shipped in the HTML before any script
# runs. The language toggle still rewrites the visible title afterwards.
META = {
    "index.html": ("Chun Kai Xin - Chinese Language Teacher and EdTech Builder",
                   "Classroom-grounded Chinese Language learning tools, designed and built by "
                   "a practising Singapore teacher."),
    "work.html": ("Work - Chun Kai Xin",
                  "VocabSummit, a Secondary Chinese Language vocabulary platform, plus other "
                  "tools built for specific classroom problems."),
    "talks.html": ("Community - Chun Kai Xin",
                   "Talks, write-ups and shared resources for other teachers, including two "
                   "SgLDC badges awarded by MOE's Educational Technology Division."),
    "approach.html": ("How I design - Chun Kai Xin",
                      "Design commitments drawn from Self-Determination Theory and Assessment "
                      "for Learning, and the block printing behind them."),
    "contact.html": ("Contact - Chun Kai Xin",
                     "Get in touch about adapting any of these tools, or about building "
                     "something together."),
}

PAGES = {
    "index.html": ("page.home.title", """\
  <section class="hero" id="top">
    <div class="wrap">
      <!-- The couplet VocabSummit is named from. Both languages always show:
           the pairing itself is the content, not a translation of it. -->
      <p class="epigraph">
        <span class="zh" lang="zh-Hans">书山有路勤为径，学海无涯苦作舟</span>
        <span class="en" lang="en">On the mountain of books, diligence is the path;
          on the sea of learning, endurance is the boat.</span>
        <span class="src" data-i18n="epigraph.source">《增广贤文 · 劝学篇》</span>
      </p>

      <p class="eyebrow">kaixinbuilds</p>
      <h1 class="hero-name" data-i18n="hero.name">Chun Kai Xin</h1>
      <p class="hero-tagline" data-i18n="hero.tagline"></p>
      <p class="hero-intro" data-i18n="hero.intro"></p>
      <p class="hero-actions">
        <a class="btn btn-primary" href="work.html" data-i18n="hero.ctaWork">See the work</a>
        <a class="btn btn-ghost" href="contact.html" data-i18n="hero.ctaContact">Get in touch</a>
      </p>
    </div>
  </section>"""),
    "work.html": ("page.work.title", """\
  <section class="section" id="work">
    <div class="wrap">
      <h1 class="page-title" data-i18n="nav.work">Work</h1>
      <p class="page-sub" data-i18n="work.intro"></p>
      <div id="featured" class="featured" aria-live="polite"></div>
    </div>
  </section>

  <section class="section">
    <div class="wrap">
      <h2 class="section-title" data-i18n="grid.title">Other projects</h2>
      <p class="section-sub" data-i18n="grid.subtitle"></p>
      <div id="project-grid" class="card-grid"></div>
    </div>
  </section>"""),
    "talks.html": ("page.talks.title", """\
  <section class="section" id="talks">
    <div class="wrap wrap-narrow">
      <h1 class="page-title" data-i18n="talks.title">Connecting with other teachers</h1>
      <p class="page-sub" data-i18n="talks.subtitle"></p>
      <ol id="talks-list" class="talks-list"></ol>
    </div>
  </section>"""),
    "approach.html": ("page.approach.title", """\
  <section class="section" id="approach">
    <div class="wrap wrap-narrow">
      <h1 class="page-title" data-i18n="approach.title">How I design</h1>
      <p class="page-sub" data-i18n="approach.body2"></p>

      <p class="lede" data-i18n="approach.body1"></p>

      <ul class="principles">
        <li>
          <h3 data-i18n="approach.principle1Title"></h3>
          <p data-i18n="approach.principle1Body"></p>
        </li>
        <li>
          <h3 data-i18n="approach.principle2Title"></h3>
          <p data-i18n="approach.principle2Body"></p>
        </li>
        <li>
          <h3 data-i18n="approach.principle3Title"></h3>
          <p data-i18n="approach.principle3Body"></p>
        </li>
      </ul>

      <!-- A real block print, presented as a labelled specimen rather than
           as decoration. Hides itself if the image is not there yet. -->
      <figure class="specimen">
        <div class="specimen-plate">
          <img src="assets/art/prints/payphone-print.png" alt=""
               data-i18n="specimen.alt" data-i18n-attr="alt" decoding="async">
        </div>
        <figcaption>
          <span class="specimen-title" data-i18n="specimen.title"></span>
          <span class="specimen-meta" data-i18n="specimen.meta"></span>
          <span class="specimen-note" data-i18n="specimen.note"></span>
        </figcaption>
      </figure>
    </div>
  </section>"""),
    "contact.html": ("page.contact.title", """\
  <section class="section" id="contact">
    <div class="wrap wrap-narrow">
      <h1 class="page-title" data-i18n="contact.title">Get in touch</h1>
      <p class="page-sub" data-i18n="contact.subtitle"></p>

      <p class="contact-direct">
        <a class="contact-email" href="mailto:kai_xin_chun@moe.edu.sg">kai_xin_chun@moe.edu.sg</a>
      </p>
      <p class="contact-repo">
        <a href="https://github.com/kaixinbuilds/kaixinbuilds.github.io">github.com/kaixinbuilds/kaixinbuilds.github.io</a>
      </p>
    </div>
  </section>"""),
}


def render(page):
    title_key, body = PAGES[page]
    nav = "\n".join(
        '        <a href="%s"%s data-i18n="%s">%s</a>'
        % (href, CURRENT if href == page else "", key, label)
        for href, key, label in NAV)

    static_title, static_desc = META[page]
    canonical = SITE + "/" + ("" if page == "index.html" else page)

    html = (HEAD
            .replace("__TITLE_KEY__", title_key)
            .replace("__STATIC_TITLE__", static_title)
            .replace("__STATIC_DESC__", static_desc)
            .replace("__CANONICAL__", canonical)
            .replace("__SHARE_IMAGE__", SHARE_IMAGE)
            .replace("__HOME__", CURRENT if page == "index.html" else "")
            .replace("__NAV__", nav + "\n"))
    return html.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + BANNER, 1) \
        + '<main id="main">\n' + body + "\n</main>" + TAIL


if __name__ == "__main__":
    for page in PAGES:
        pathlib.Path(page).write_text(render(page))
        print("built", page)
