#!/usr/bin/env python3
"""Regenerate the site's HTML pages from one shared shell.

Every page carries the same head, header and footer. Holding that in one
place means a nav change is a single edit rather than five, and no page can
quietly drift out of step with the others.

    python3 build.py

publish.sh runs this before every commit, so the HTML in the repo is always
this file's output. Edit this file, never the .html files: they are
overwritten on the next build.
"""
import json, pathlib, re

BANNER = "<!-- Generated by build.py. Edit build.py, not this file. -->"

# (file, i18n key for the nav label, fallback text)
NAV = [
    ("work.html", "nav.work", "Work"),
    ("talks.html", "nav.talks", "Connect"),
    ("approach.html", "nav.approach", "Practice"),
    ("contact.html", "nav.contact", "Contact"),
]

CURRENT = ' aria-current="page"'

HEAD = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title data-i18n="__TITLE_KEY__">__STATIC_TITLE__</title>
<meta name="description" data-i18n="site.description" data-i18n-attr="content" content="__STATIC_DESC__">
<link rel="canonical" href="__CANONICAL__">

<meta property="og:type" content="website">
<meta property="og:site_name" content="kaixinbuilds">
<meta property="og:title" content="__STATIC_TITLE__">
<meta property="og:description" content="__STATIC_DESC__">
<meta property="og:url" content="__CANONICAL__">
<meta property="og:image" content="__SHARE_IMAGE__">
<meta name="twitter:card" content="summary_large_image">
<meta name="color-scheme" content="light">
<meta name="theme-color" content="#1E2749">

<!-- Spectral for headings and epigraphs, Inter for body and UI. Chinese
     resolves to the system serif (Songti SC / Source Han Serif): a webfont
     with CJK coverage would cost megabytes for one page. -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Spectral:ital,wght@0,400;0,600;1,400&display=swap" rel="stylesheet">

<link rel="stylesheet" href="style.css">
<link rel="icon" href="favicon.png" sizes="48x48">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
</head>
<body>

<a class="skip-link" href="#main">Skip to content</a>

<header class="site-header">
  <div class="wrap">
    <div class="header-inner">
      <a class="wordmark" href="index.html"__HOME__>
        <img class="mark" src="favicon.png" alt="" width="22" height="22" decoding="async">
        <span class="wordmark-text" id="wordmark-text">kaixin<em>builds</em></span>
      </a>

      <nav class="site-nav" aria-label="Primary">
__NAV__      </nav>

      <!-- Three modes, like the game: Chinese, both, English. The labels are
           language names, so they are never themselves translated. -->
      <div id="lang-switch" class="lang-switch" role="group" aria-label="Language / 语言">
        <button type="button" data-lang="zh" lang="zh-Hans">华文</button>
        <button type="button" data-lang="both" lang="zh-Hans">双语</button>
        <button type="button" data-lang="en" lang="en">English</button>
      </div>
    </div>
  </div>
</header>

"""

TAIL = """\


<script src="script.js"></script>
</body>
</html>
"""

SITE = "https://kaixinbuilds.github.io"
SHARE_IMAGE = SITE + "/assets/social-card.jpg"

# (static <title>, static description) shipped in the HTML before any script
# runs. The language toggle still rewrites the visible title afterwards.
META = {
    "index.html": ("Chun Kai Xin - Learning Designer",
                   "Classroom-grounded Chinese Language learning tools, designed and built by "
                   "a practising Singapore teacher."),
    "work.html": ("Work - Chun Kai Xin",
                  "VocabSummit, a Secondary Chinese Language vocabulary platform, plus other "
                  "tools built for specific classroom problems."),
    "talks.html": ("Connect - Chun Kai Xin",
                   "Talks, write-ups and shared resources for other teachers, including two "
                   "SgLDC badges awarded by MOE's Educational Technology Division."),
    "approach.html": ("Practice - Chun Kai Xin",
                      "How a classroom tool actually gets designed: a short loop where the "
                      "deciding step is students using it in a real lesson."),
    "2026AIinSecCLNLC.html": ("2026 AI in Sec CL NLC - Chun Kai Xin",
                              "Resources for the 28 August 2026 AI in Sec CL NLC workshop: the five pieces of technology behind VocabSummit, and a starter game to adapt for your own unit."),
    "contact.html": ("Contact - Chun Kai Xin",
                     "Get in touch about adapting any of these tools, or about building "
                     "something together."),
}

PAGES = {
    "index.html": ("page.home.title", """\
  <section class="hero" id="top">
    <div class="wrap">
      <!-- The couplet VocabSummit is named from. Both languages always show:
           the pairing itself is the content, not a translation of it. -->
      <p class="epigraph">
        <span class="zh" lang="zh-Hans">不满是向上的车轮</span>
        <span class="en" lang="en">Discontent is the wheel that carries us forward.</span>
        <span class="src" data-i18n="epigraph.source">鲁迅</span>
      </p>

      <p class="eyebrow" data-i18n="brand.full">kaixinbuilds</p>
      <h1 class="hero-name" data-i18n="hero.name">Chun Kai Xin</h1>
      <p class="hero-tagline" data-i18n="hero.tagline"></p>
      <p class="hero-intro" data-i18n="hero.intro"></p>
      <p class="hero-actions">
        <a class="btn btn-primary" href="work.html" data-i18n="hero.ctaWork">See my work</a>
        <a class="btn btn-ghost" href="contact.html" data-i18n="hero.ctaContact">Get in touch</a>
      </p>
    </div>
  </section>"""),
    "work.html": ("page.work.title", """\
  <section class="section" id="work">
    <div class="wrap">
      <h1 class="page-title" data-i18n="nav.work">Work</h1>
      <p class="page-sub" data-i18n="work.intro"></p>

      <div class="work-layout">
        <!-- An index of everything, and one project open at a time. Without
             JavaScript every panel simply shows, stacked. -->
        <nav id="project-nav" class="project-nav" aria-label="Projects"></nav>
        <div id="project-detail" class="project-detail"></div>
      </div>
    </div>
  </section>"""),
    "talks.html": ("page.talks.title", """\
  <section class="section" id="talks">
    <div class="wrap">
      <h1 class="page-title" data-i18n="talks.title">Connect</h1>

      <div class="work-layout">
        <!-- Built by script.js from talks.json, same shape as the Work index. -->
        <nav id="talk-nav" class="project-nav" aria-label="Talks"></nav>
        <div id="talks-list"></div>
      </div>
    </div>
  </section>"""),
    "approach.html": ("page.approach.title", """  <section class="section" id="approach">
    <div class="wrap wrap-narrow">
      <h1 class="page-title" data-i18n="approach.title">Practice</h1>

      <!-- A couplet for the philosophy, in parallel with the one that names
           the flagship project on the home page. -->
      <p class="epigraph">
        <span class="zh" lang="zh-Hans">纸上得来终觉浅，绝知此事要躬行</span>
        <span class="en" lang="en">What is learnt on paper stays shallow.
          To truly know a thing, you have to do it yourself.</span>
        <span class="src">陆游《冬夜读书示子聿》</span>
      </p>

      <p class="lede" data-i18n="approach.leadA"></p>

      <!-- The five stages of the design thinking cycle, named and nothing
           more: the heading is the stage, and what happened while building
           VocabSummit is answered underneath in the fewest words that carry
           it. The point counts differ by stage because the stages differ; a
           stage is not padded to match its neighbours. -->
      <ol class="loop">
        <li>
          <h2 data-i18n="approach.loop1Title"></h2>
          <ul class="loop-points">
            <li data-i18n="approach.loop1P1"></li>
            <li data-i18n="approach.loop1P2"></li>
            <li data-i18n="approach.loop1P3"></li>
          </ul>
        </li>
        <li>
          <h2 data-i18n="approach.loop2Title"></h2>
          <ul class="loop-points">
            <li data-i18n="approach.loop2P1"></li>
            <li data-i18n="approach.loop2P2"></li>
            <li data-i18n="approach.loop2P3"></li>
            <li data-i18n="approach.loop2P4"></li>
          </ul>
        </li>
        <li>
          <h2 data-i18n="approach.loop3Title"></h2>
          <ul class="loop-points">
            <li data-i18n="approach.loop3P1"></li>
            <li data-i18n="approach.loop3P2"></li>
            <li data-i18n="approach.loop3P3"></li>
            <li data-i18n="approach.loop3P4"></li>
          </ul>
        </li>
        <li>
          <h2 data-i18n="approach.loop4Title"></h2>
          <ul class="loop-points">
            <li data-i18n="approach.loop4P1"></li>
            <li data-i18n="approach.loop4P2"></li>
            <li data-i18n="approach.loop4P3"></li>
            <li data-i18n="approach.loop4P4"></li>
          </ul>
        </li>
        <li>
          <h2 data-i18n="approach.loop5Title"></h2>
          <ul class="loop-points">
            <li data-i18n="approach.loop5P1"></li>
            <li data-i18n="approach.loop5P2"></li>
            <li data-i18n="approach.loop5P3"></li>
          </ul>
        </li>
      </ol>

      <p class="loop-close" data-i18n="approach.loopClose"></p>

      <!-- The loop above is how the thing gets made. This is what it is aimed
           at, and it is the spine of the SPMC sharing: Self-Determination
           Theory turns "make vocabulary fun" into three answerable questions,
           and every feature listed here exists to answer one of them. Each
           need opens with the student sentence it is a reply to. -->
      <section class="needs-block" aria-labelledby="needs-title">
        <h2 class="section-title" id="needs-title" data-i18n="approach.needsTitle"></h2>
        <p class="lede" data-i18n="approach.needsLead"></p>

        <div class="needs">
          <article class="need">
            <p class="need-name" data-i18n="approach.need1Name"></p>
            <p class="need-voice" data-i18n="approach.need1Voice"></p>
            <h3 data-i18n="approach.need1Q"></h3>
            <ul class="loop-points need-points">
              <li data-i18n="approach.need1P1"></li>
              <li data-i18n="approach.need1P2"></li>
              <li data-i18n="approach.need1P3"></li>
              <li data-i18n="approach.need1P4"></li>
            </ul>
          </article>
          <article class="need">
            <p class="need-name" data-i18n="approach.need2Name"></p>
            <p class="need-voice" data-i18n="approach.need2Voice"></p>
            <h3 data-i18n="approach.need2Q"></h3>
            <ul class="loop-points need-points">
              <li data-i18n="approach.need2P1"></li>
              <li data-i18n="approach.need2P2"></li>
              <li data-i18n="approach.need2P3"></li>
              <li data-i18n="approach.need2P4"></li>
            </ul>
          </article>
          <article class="need">
            <p class="need-name" data-i18n="approach.need3Name"></p>
            <p class="need-voice" data-i18n="approach.need3Voice"></p>
            <h3 data-i18n="approach.need3Q"></h3>
            <ul class="loop-points need-points">
              <li data-i18n="approach.need3P1"></li>
              <li data-i18n="approach.need3P2"></li>
              <li data-i18n="approach.need3P3"></li>
            </ul>
          </article>
        </div>

        <p class="needs-close">
          <span data-i18n="approach.needsClose"></span>
          <a href="talks.html" data-i18n="approach.needsLink"></a>
        </p>
      </section>

    </div>
  </section>"""),
    "2026AIinSecCLNLC.html": ("page.nlc26.title", """\
  <section class="section" id="nlc">
    <div class="wrap">
      <p class="eyebrow" data-i18n="nlc26.eyebrow">2026 AI in Sec CL NLC</p>
      <h1 class="page-title" data-i18n="nlc26.title">Splitting heaven and earth with an AI axe</h1>

      <!-- Order follows the session itself: what we are here to do, the
           practicalities, the thing being shown, how it was made, the tools
           behind it, then the two hours of hands-on, then the objections. -->
      <div class="work-layout">
        <nav class="project-nav" aria-label="On this page">
          <ul>
            <li><a href="#goals" data-i18n="nlc26.navGoals"></a></li>
            <li><a href="#session" data-i18n="nlc26.navSession"></a></li>
            <li><a href="#vocabsummit" data-i18n="nlc26.navVs"></a></li>
            <li><a href="#how-it-started" data-i18n="nlc26.navStory"></a></li>
            <li><a href="#stack" data-i18n="nlc26.navStack"></a></li>
            <li><a href="#hands-on" data-i18n="nlc26.navHands"></a></li>
            <li><a href="#concerns" data-i18n="nlc26.navQ"></a></li>
          </ul>
        </nav>

        <div class="project-detail">

          <div class="doc-block" id="goals">
            <h2 class="section-title" data-i18n="nlc26.goalsTitle"></h2>
            <!-- Numbered, because two targets in order is what a sprint is.
                 An <ol> here rather than the big circled .loop: at the top of
                 the page these are the goal, not a procedure to work through. -->
            <ol class="loop-points loop-points-num">
              <li data-i18n="nlc26.goal1"></li>
              <li data-i18n="nlc26.goal2"></li>
            </ol>
          </div>

          <div class="doc-block" id="session">
            <!-- Presenter first, logistics after: how a session programme
                 lists a session. Audience last, because it scopes the rest. -->
            <ul class="loop-points">
              <li data-i18n="nlc26.dSpeaker"></li>
              <li data-i18n="nlc26.dDate"></li>
              <li data-i18n="nlc26.dTime"></li>
              <li data-i18n="nlc26.dVenue"></li>
              <li data-i18n="nlc26.dAudience"></li>
            </ul>
          </div>

          <div class="doc-block" id="vocabsummit">
            <h2 class="section-title" data-i18n="nlc26.vsTitle"></h2>
            <ul class="stats">
              <li><span class="value">3,889</span><span class="label" data-i18n="nlc26.statWords"></span></li>
              <li><span class="value">3</span><span class="label" data-i18n="nlc26.statClasses"></span></li>
              <li><span class="value">47</span><span class="label" data-i18n="nlc26.statStudents"></span></li>
              <li><span class="value">1</span><span class="label" data-i18n="nlc26.statPeople"></span></li>
            </ul>

            <div class="shots">
        <figure class="shot shot-wide">
          <div class="screen-bezel">
            <div class="screen-inner" data-missing="assets/screenshots/vocabsummit-landing.jpg">
              <img src="assets/screenshots/vocabsummit-landing.jpg" alt="" data-i18n="nlc26.shot1" data-i18n-attr="alt" decoding="async">
            </div>
          </div>
          <figcaption data-i18n="nlc26.shot1"></figcaption>
        </figure>
        <figure class="shot">
          <div class="screen-bezel">
            <div class="screen-inner" data-missing="assets/screenshots/vocabsummit-mountain.jpg">
              <img src="assets/screenshots/vocabsummit-mountain.jpg" alt="" data-i18n="nlc26.shot2" data-i18n-attr="alt" decoding="async">
            </div>
          </div>
          <figcaption data-i18n="nlc26.shot2"></figcaption>
        </figure>
        <figure class="shot">
          <div class="screen-bezel">
            <div class="screen-inner" data-missing="assets/screenshots/vocabsummit-dashboard.jpg">
              <img src="assets/screenshots/vocabsummit-dashboard.jpg" alt="" data-i18n="nlc26.shot3" data-i18n-attr="alt" decoding="async">
            </div>
          </div>
          <figcaption data-i18n="nlc26.shot3"></figcaption>
        </figure>
            </div>

            <p class="featured-cta">
              <a class="btn btn-primary" href="https://btvssclunit.github.io/VocabSummit"
                 data-i18n="nlc26.vsCta" target="_blank" rel="noopener">Open VocabSummit</a>
              <a class="btn btn-ghost" href="work.html" data-i18n="nlc26.vsWork">The project write-up</a>
              <a class="btn btn-ghost" href="approach.html" data-i18n="nlc26.vsApproach">How it was designed</a>
            </p>
          </div>

          <!-- A transition, and a disarming one: it began as one message. -->
          <div class="doc-block" id="how-it-started">
            <h2 class="section-title" data-i18n="nlc26.storyTitle"></h2>

            <!-- Hardcoded, not translated: a transcript, not copy. -->
            <div class="copy-block">
              <span class="cap" data-i18n="nlc26.storyCap"></span>
              <pre lang="en">I want to build a powerful secondary school revision tool on SLS
(student learning space) for students to revise all CL vocab covered
over 4 years, and for it to be trackable to let them see their progress,
so that they can revisit the vocab that they have yet to master.

I don't know how to start, could you help me?
https://www.learning.moe.edu.sg/teacher-user-guide/author/html5-content-development/</pre>
            </div>

            <ul class="loop-points">
              <li data-i18n="nlc26.storyP2"></li>
            </ul>

            <div class="highlight-box">
              <p data-i18n="nlc26.storyClose"></p>
            </div>
          </div>

          <div class="doc-block" id="stack">
            <h2 class="section-title" data-i18n="nlc26.stackTitle"></h2>
            <p class="section-sub" data-i18n="nlc26.stackLede"></p>
            <!-- The founder leads, because the ordering is the argument:
                 the five that follow are hired, and not one of them decides
                 anything. Two lines each, no more. -->
            <!-- The founder leads, because the ordering is the argument:
                 the five that follow are hired, and not one of them decides
                 anything. One line each: the role and the who are already in
                 the heading, so the line only has to say what they do. -->
            <ol class="loop">
        <li>
          <h3 data-i18n="nlc26.p1Title"></h3>
          <p class="loop-cycle" data-i18n="nlc26.p1Cycle"></p>
          <ul class="loop-points">
            <li data-i18n="nlc26.p1A"></li>
          </ul>
        </li>
        <li>
          <h3 data-i18n="nlc26.p2Title"></h3>
          <p class="loop-cycle" data-i18n="nlc26.p2Cycle"></p>
          <ul class="loop-points">
            <li data-i18n="nlc26.p2A"></li>
          </ul>
        </li>
        <li>
          <h3 data-i18n="nlc26.p3Title"></h3>
          <p class="loop-cycle" data-i18n="nlc26.p3Cycle"></p>
          <ul class="loop-points">
            <li data-i18n="nlc26.p3A"></li>
          </ul>
        </li>
        <li>
          <h3 data-i18n="nlc26.p4Title"></h3>
          <p class="loop-cycle" data-i18n="nlc26.p4Cycle"></p>
          <ul class="loop-points">
            <li data-i18n="nlc26.p4A"></li>
          </ul>
        </li>
        <li>
          <h3 data-i18n="nlc26.p5Title"></h3>
          <p class="loop-cycle" data-i18n="nlc26.p5Cycle"></p>
          <ul class="loop-points">
            <li data-i18n="nlc26.p5A"></li>
            <li data-i18n="nlc26.p5B"></li>
          </ul>
        </li>
        <li>
          <h3 data-i18n="nlc26.p6Title"></h3>
          <p class="loop-cycle" data-i18n="nlc26.p6Cycle"></p>
          <ul class="loop-points">
            <li data-i18n="nlc26.p6A"></li>
          </ul>
        </li>
            </ol>
          </div>

          <!-- Four stages, not six steps. Stage 1 is the floor everyone leaves
               with; stages 2 to 4 are differentiation, and they are named for
               what changes rather than for who got that far. The cycle labels
               borrow VocabSummit's own chapter components, so the session and
               the platform it is about speak the same vocabulary. -->
          <div class="doc-block" id="hands-on">
            <h2 class="section-title" data-i18n="nlc26.handsTitle"></h2>
            <p class="section-sub" data-i18n="nlc26.handsLede"></p>
            <p class="lede" data-i18n="nlc26.handsFloor"></p>

            <p class="featured-cta">
              <a class="btn btn-primary" href="https://github.com/kaixinbuilds/VocabClimbStarter"
                 data-i18n="nlc26.handsCta" target="_blank" rel="noopener">Open the starter</a>
              <a class="btn btn-ghost" href="https://claude.ai" data-i18n="nlc26.handsClaude"
                 target="_blank" rel="noopener">claude.ai</a>
            </p>

            <ol class="loop">
        <li>
          <h3 data-i18n="nlc26.s1Title"></h3>
          <p class="loop-cycle" data-i18n="nlc26.s1Cycle"></p>
          <ul class="loop-points">
            <li data-i18n="nlc26.s1P1"></li>
            <li data-i18n="nlc26.s1P2"></li>
            <li data-i18n="nlc26.s1P3"></li>
            <li data-i18n="nlc26.s1P4"></li>
            <li data-i18n="nlc26.s1P5"></li>
            <li data-i18n="nlc26.s1P6"></li>
          </ul>
        </li>
        <li>
          <h3 data-i18n="nlc26.s2Title"></h3>
          <p class="loop-cycle" data-i18n="nlc26.s2Cycle"></p>
          <ul class="loop-points">
            <li data-i18n="nlc26.s2P1"></li>
            <li data-i18n="nlc26.s2P2"></li>
          </ul>

          <div class="copy-block">
            <span class="cap" data-i18n="nlc26.promptCap"></span>
            <pre lang="zh-Hans">我是中学华文老师，不会编码。
我已经把一个小游戏的整个资料夹和一份词语表格上传到这个 Project 里。

请帮我做三件事：
1. 读我上传的表格，把里面的词语和释义，照 my-words.js 原本的格式
   重新写成一个完整的 my-words.js 给我下载。格式不要动，只换内容。
2. 把 UNIT_NAME 改成：〔你的单元名称〕
3. 把 SECONDS 改成：〔90〕

改好之后直接给我可以下载的 my-words.js，并告诉我放回哪个位置。

如果我的表格有问题（缺了释义、词语重复、少于 8 个），请先告诉我，不要自己猜。</pre>
          </div>

          <ul class="loop-points">
            <li data-i18n="nlc26.s2P3"></li>
            <li data-i18n="nlc26.s2P4"></li>
          </ul>
        </li>
        <li>
          <h3 data-i18n="nlc26.s3Title"></h3>
          <p class="loop-cycle" data-i18n="nlc26.s3Cycle"></p>
          <ul class="loop-points">
            <li data-i18n="nlc26.s3P1"></li>
            <li data-i18n="nlc26.s3P2"></li>
          </ul>

          <!-- The three art files only. Editing the colours in index.html
               means editing the game's own source, which is a different kind
               of risk from dropping in a picture, and this stage is not the
               place to introduce it. -->
          <div class="copy-block">
            <span class="cap" data-i18n="nlc26.promptCap"></span>
            <pre lang="zh-Hans">我已经把这个游戏的整个资料夹上传到这个 Project 里了。

告诉我 art 资料夹里那三张图（landscape.jpg、wall.jpg、climber.png）
分别是做什么用的、该做多大，我想自己换掉。</pre>
          </div>
        </li>
        <li>
          <h3 data-i18n="nlc26.s4Title"></h3>
          <p class="loop-cycle" data-i18n="nlc26.s4Cycle"></p>
          <ul class="loop-points">
            <li data-i18n="nlc26.s4P1"></li>
            <li data-i18n="nlc26.s4P2"></li>
            <li data-i18n="nlc26.s4P3"></li>
            <li data-i18n="nlc26.s4P4"></li>
          </ul>

          <!-- No starter folder at this stage, on purpose: this is the one that
               simulates being alone with the agent. The prompt is a shape rather
               than a script, and it is mostly blanks, because the move being
               taught is problem first, options before building. -->
          <div class="copy-block">
            <span class="cap" data-i18n="nlc26.promptCapS4"></span>
            <pre lang="zh-Hans">我是中学华文老师，不会编码。

我班上遇到的问题是：〔用两三句话说清楚，先别说你要什么工具〕
我的学生是：〔中几、什么程度〕
我手上现成的材料有：〔词表？课文？考卷？录音？图片？〕

请先别动手做。先给我三个不一样的做法，每一个用三四句话说明：
学生会看到什么、要做什么、你为什么觉得这个做法对得上我的问题。

我挑好了再告诉你，那时候才开始做。
做出来的东西要能直接放上 GitHub Pages，跟我今天做的那个一样。

我不会编码。任何要我自己动手的地方，请写清楚点哪里、贴哪一段。</pre>
          </div>
        </li>
            </ol>

            <!-- One box, not three: everything you reach for when it goes wrong. -->
            <div class="highlight-box">
              <span class="label" data-i18n="nlc26.stuckLabel"></span>
              <ul class="loop-points">
                <li data-i18n="nlc26.stuck1"></li>
                <li data-i18n="nlc26.stuck2"></li>
                <li data-i18n="nlc26.stuck3"></li>
                <li data-i18n="nlc26.stuck4"></li>
                <li data-i18n="nlc26.stuck5"></li>
                <li data-i18n="nlc26.stuck6"></li>
              </ul>
            </div>
          </div>

          <div class="doc-block" id="concerns">
            <h2 class="section-title" data-i18n="nlc26.qTitle"></h2>
            <ol class="loop">
        <li>
          <h3 data-i18n="nlc26.q1"></h3>
          <ul class="loop-points">
            <li data-i18n="nlc26.q1A"></li>
            <li data-i18n="nlc26.q1B"></li>
            <li data-i18n="nlc26.q1C"></li>
          </ul>
        </li>
        <li>
          <h3 data-i18n="nlc26.q2"></h3>
          <ul class="loop-points">
            <li data-i18n="nlc26.q2A"></li>
            <li data-i18n="nlc26.q2B"></li>
            <li data-i18n="nlc26.q2C"></li>
          </ul>
        </li>
        <li>
          <h3 data-i18n="nlc26.q3"></h3>
          <ul class="loop-points">
            <li data-i18n="nlc26.q3A"></li>
            <li data-i18n="nlc26.q3B"></li>
            <li data-i18n="nlc26.q3C"></li>
          </ul>
        </li>
        <li>
          <h3 data-i18n="nlc26.q4"></h3>
          <ul class="loop-points">
            <li data-i18n="nlc26.q4A"></li>
            <li data-i18n="nlc26.q4B"></li>
            <li data-i18n="nlc26.q4C"></li>
          </ul>
        </li>
            </ol>

            <!-- The community's own motto, quoted back to it, set as a colophon.
                 It closed the page when there was an "afterwards" section; with
                 that gone it closes the page directly. -->
            <p class="epigraph colophon">
              <span class="zh" lang="zh-Hans">地上本无路，走的人多了，便成了路</span>
              <span class="en" lang="en">The earth had no roads to begin with. When enough
                people walk the same way, a road appears.</span>
              <span class="src" data-i18n="nlc26.epigraphSrc"></span>
            </p>
          </div>

        </div>
      </div>
    </div>
  </section>"""),
    "contact.html": ("page.contact.title", """\
  <section class="section" id="contact">
    <div class="wrap">
      <h1 class="page-title" data-i18n="contact.title">Get in touch</h1>
      <p class="page-sub" data-i18n="contact.subtitle"></p>

      <div class="contact-layout">
        <div class="contact-details">
          <p class="contact-direct">
            <span class="contact-label" data-i18n="contact.emailLabel"></span>
            <a class="contact-email" href="mailto:kai_xin_chun@moe.edu.sg">kai_xin_chun@moe.edu.sg</a>
          </p>
        </div>

        <!-- Hung and labelled the way a print would be in a gallery, rather
             than used as decoration. Hides itself if the image is missing. -->
        <figure class="specimen">
          <div class="specimen-plate">
            <img src="assets/art/prints/payphone-block-print.png" alt=""
                 data-i18n="specimen.alt" data-i18n-attr="alt" decoding="async">
          </div>
          <figcaption class="specimen-label">
            <span class="specimen-title" data-i18n="specimen.title"></span>
            <span class="specimen-artist" data-i18n="specimen.artist"></span>
            <span class="specimen-meta" data-i18n="specimen.meta"></span>
          </figcaption>
        </figure>
      </div>

      <!-- The name, glossed. 观象制器 carries an allusion not every reader
           will catch, so the last page states it plainly. Same device as the
           epigraphs, set as a colophon: it closes a page instead of opening
           one. -->
      <p class="epigraph colophon">
        <span class="zh" lang="zh-Hans">观象制器</span>
        <span class="en" lang="en">Observe the pattern, then make the tool.</span>
        <span class="src" data-i18n="colophon.source"></span>
      </p>
    </div>
  </section>"""),
}


def render(page):
    title_key, body = PAGES[page]
    nav = "\n".join(
        '        <a href="%s"%s data-i18n="%s">%s</a>'
        % (href, CURRENT if href == page else "", key, label)
        for href, key, label in NAV)

    static_title, static_desc = META[page]
    canonical = SITE + "/" + ("" if page == "index.html" else page)

    html = (HEAD
            .replace("__TITLE_KEY__", title_key)
            .replace("__STATIC_TITLE__", static_title)
            .replace("__STATIC_DESC__", static_desc)
            .replace("__CANONICAL__", canonical)
            .replace("__SHARE_IMAGE__", SHARE_IMAGE)
            .replace("__HOME__", CURRENT if page == "index.html" else "")
            .replace("__NAV__", nav + "\n"))
    return html.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + BANNER, 1) \
        + '<main id="main">\n' + body + "\n</main>" + TAIL


def write_sitemap():
    """A sitemap and a robots.txt, so search engines can find every page and
    know where the sitemap lives. No lastmod: it would change on every build
    whether or not the content did, for no real benefit."""
    urls = "\n".join(
        "  <url><loc>%s</loc><priority>%s</priority></url>"
        % (SITE + "/" + ("" if p == "index.html" else p), "1.0" if p == "index.html" else "0.8")
        for p in PAGES)
    pathlib.Path("sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + urls + "\n</urlset>\n")
    pathlib.Path("robots.txt").write_text(
        "User-agent: *\n"
        "Allow: /\n\n"
        "Sitemap: %s/sitemap.xml\n" % SITE)
    # Every page here is finished HTML. Jekyll has nothing to contribute, and
    # a Jekyll build that fails takes the whole deploy down with it, silently:
    # Pages keeps serving the last good commit and the site simply stops
    # updating. This empty file turns Jekyll off, so Pages just serves files.
    pathlib.Path(".nojekyll").write_text("")


def check_i18n():
    """Every key the pages ask for must exist, and every nlc26 key must be asked
    for. A page that references a deleted key renders the key name at readers,
    which shipped once and was seen. This makes that a build failure instead."""
    i18n = json.loads(pathlib.Path("i18n.json").read_text())
    asked = set()
    for page in PAGES:
        html = pathlib.Path(page).read_text()
        asked |= set(re.findall(r'data-i18n(?:-aria-label)?="([^"]+)"', html))

    missing = sorted(k for k in asked if k not in i18n)
    # Only nlc26 is checked for orphans: the other namespaces are shared across
    # pages and rendered from JSON, so an unused key there is not a mistake.
    orphans = sorted(k for k in i18n
                     if k.startswith("nlc26.") and k not in asked)

    if missing:
        print("\nBUILD FAILED. These keys are on a page but not in i18n.json:")
        for k in missing:
            print("   ", k)
        print("\nEither add them to i18n.json or take them out of build.py.")
        raise SystemExit(1)
    if orphans:
        print("\nUnused nlc26 keys still in i18n.json (harmless, but tidy up):")
        for k in orphans:
            print("   ", k)
    print("i18n keys check out")


if __name__ == "__main__":
    for page in PAGES:
        pathlib.Path(page).write_text(render(page))
        print("built", page)
    write_sitemap()
    print("built sitemap.xml, robots.txt and .nojekyll")
    check_i18n()
